# Scenario configuration for HOCBF controller test

hocbf_controller:
  ros__parameters:
    goal_ee_pos:
    - 0.3068
    - -0.65
    - 0.55
    gamma_js: 2.0
    beta_js: 3.0
    d_margin: 0.0
    output_data_basename: scenario_0
    goal_maintolerance_m: 0.02
    goal_settle_time_s: 1.5
    max_sim_duration_s: 60.0
obstacles:
- name: obstacle_0
  pose_start:
    position:
    - 0.3068
    - 0.27
    - 0.55
  pose_end:
    position:
    - 0.3068
    - 0.27
    - 0.55
  size:
    radius: 0.15
  velocity:
    linear:
    - 0.0
    - 0.0
    - 0.0
- name: obstacle_1
  pose_start:
    position:
    - 0.3068
    - -0.27
    - 0.55
  pose_end:
    position:
    - 0.3068
    - -0.27
    - 0.55
  size:
    radius: 0.15
  velocity:
    linear:
    - 0.0
    - 0.0
    - 0.0
